[package]
name = "rudis"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "client"
path = "src/client/client.rs"

[[bin]]
name = "serve"
path = "src/server/serve.rs"

[dependencies]
redis = "0.23.3"
